(() => {
  let recording=false; let events=[]; let hoverEl=null;
  const escape=(v)=>window.CSS?.escape?CSS.escape(v):v.replace(/[^a-zA-Z0-9_-]/g,'\\$&');
  const cssPath=(el)=>{if(el.id)return `#${escape(el.id)}`;const p=[];let n=el;while(n&&n!==document.body&&n.parentElement){let i=1;for(let s=n.previousElementSibling;s;s=s.previousElementSibling)if(s.tagName===n.tagName)i++;p.unshift(`${n.tagName.toLowerCase()}:nth-of-type(${i})`);n=n.parentElement;}return p.join(' > ');};
  const xpath=(el)=>{if(el.id)return `//*[@id=${JSON.stringify(el.id)}]`;const p=[];let n=el;while(n&&n.nodeType===1){let i=1;for(let s=n.previousElementSibling;s;s=s.previousElementSibling)if(s.tagName===n.tagName)i++;p.unshift(`${n.tagName.toLowerCase()}[${i}]`);n=n.parentElement;}return `/${p.join('/')}`;};
  const describe=(el)=>({tag:el.tagName.toLowerCase(),text:(el.textContent||'').trim().replace(/\s+/g,' ').slice(0,120),id:el.id||undefined,name:el.getAttribute('name')||undefined,type:el.getAttribute('type')||undefined,role:el.getAttribute('role')||undefined,selectors:[...(el.id?[{kind:'id',value:el.id,priority:1}]:[]),...(el.getAttribute('name')?[{kind:'name',value:el.getAttribute('name'),priority:2}]:[]),{kind:'css',value:cssPath(el),priority:3},{kind:'xpath',value:xpath(el),priority:4},...((el.textContent||'').trim()?[{kind:'text',value:(el.textContent||'').trim().replace(/\s+/g,' ').slice(0,120),priority:5}]:[])]});
  const capture=(type,e)=>{if(!recording)return;const el=e.target instanceof Element?e.target:null;if(!el||el.closest('[data-booking-flow-admin]'))return;events.push({id:crypto.randomUUID(),at:Date.now(),type,url:location.href,element:describe(el),value:type==='input'||type==='change'?(el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement||el instanceof HTMLSelectElement?el.value:undefined):undefined});};
  const start=()=>{if(recording)return;recording=true;events=[];document.addEventListener('click',e=>capture('click',e),true);document.addEventListener('input',e=>capture('input',e),true);document.addEventListener('change',e=>capture('change',e),true);};
  const stop=()=>{recording=false;return events.slice();};
  chrome.runtime.onMessage.addListener((m,_,send)=>{if(m.type==='START_RECORDING'){start();send({ok:true});}else if(m.type==='STOP_RECORDING'){send({ok:true,events:stop()});}else if(m.type==='GET_RECORDING'){send({ok:true,events});}return true;});
  chrome.runtime.onMessage.addListener((m)=>{if(m.type==='HIGHLIGHT_SELECTOR'){document.querySelectorAll('[data-flow-highlight]').forEach(e=>e.removeAttribute('data-flow-highlight'));try{const e=document.querySelector(m.selector);if(e){e.setAttribute('data-flow-highlight','true');e.scrollIntoView({block:'center'});}}catch{}}});
  const style=document.createElement('style');style.textContent='[data-flow-highlight]{outline:3px solid #7c3aed!important;outline-offset:3px!important}';document.documentElement.appendChild(style);
})();
